Repository ass-a-service/ajobot, pull requests merged in 2022-06, with the labels that each got.

#36 Fixed andoni
  src/exts/ajo.py
Labels: bug

#42 Feat/roulette
  entrypoint.sh
  src/exts/ajo.py
  src/impl/ajo/manager.py
  src/lua/roulette.lua
  src/lua/roulette_shot.lua
Labels: feature request

#46 Feat/xstream axel
  entrypoint.sh
  src/exts/ajo.py
  src/exts/vampires.py
  src/impl/ajo/manager.py
  src/lua/farm_inventory.lua
Labels: help wanted

#48 Feat/xstream axel
  .vscode/settings.json
  entrypoint.sh
  poetry.lock
  src/__main__.py
  src/exts/ajo.py
  src/exts/vampires.py
  src/impl/ajo/manager.py
  src/lua/discombobulate.lua
  src/lua/farm_inventory.lua
  src/lua/gamble.lua
  src/lua/pay.lua
  src/lua/roulette.lua
  src/lua/roulette_shot.lua
  src/lua/timely_reward.lua
  src/lua/use_chopsticks.lua
  src/lua/use_cross.lua
  util/test.py
Labels: feature request
